
import Header from "../Login-Components/header";

import Footer from "./Footer";

export default function Layout({ children }) {
  return (
    <>
        <title>GPT-3 Answers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Header/>
      <div className="container-xl mx-auto home-body  ">
        <main>
          {children}
          {/* <Footer /> */}
        </main>
      </div>
    </>
  );
}
